### PR TITLE
Something wrong with it

### PR DESCRIPTION
**Pull request by Y2Nk4**
I have been solved it.
It is not work because of the regular expression

### CODE REVIEW

**Comment by jayceguo** [comment]
The code is from your node-steam-totp

**Comment by DoctorMcKay** [comment]
Do you think you could possibly be any less descriptive?

**Comment by jayceguo** [comment]
Maybe

**Comment by jayceguo** [comment]
I tried your code in my service,but it return a wrong auth code.
I rewrite it like what you do in your another project.
I think you should try to debug it.

**Comment by DoctorMcKay** [comment]
There is "something wrong" with your "fix". What you've done is broken the ability to pass in a binary string containing the decoded secret directly.

**Pull request closed without merging**
